### ISSUE TITLE
[Major] Posts disappear from the feed after refresh

### ISSUE THREAD

**Issue by palashgujrathi** [info442-aut21/c-team#100]
Description: After creating a new post and refreshing the page, the created post disappears.
Expected: I expected it to be there even after I refresh my browser. 
Environment: macOS Monterey Safari Version 15.1 (17612.2.9.1.20)

**Comment by julianedelossantos** [comment]
-this issue was able to be reproduced on Windows 11 Chrome Browser
-The functionality of the post feature was not complete during phase 6, but we will work on connecting the created posts to both a new post object and the logged-in user object in our database to be rendered indefinitely
