### ISSUE TITLE
[Minor] Save/favorite button not functional on profile page

### ISSUE THREAD

**Issue by victoriathegr8** [info442-aut21/c-team#101]
Upon navigating to the profile page and viewing the profile's posts, the star button is non-functional.
Chrome v96.0.4664.45 on Windows 10
1. Navigate to profile page
2. Scroll to posts section
3. Click on star button
Expected result: move/delete posts from saved, highlight star
Actual result: no change

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/98

**Comment by cherimarie** [comment]
For grading purposes, I won't be marking this as a duplicate, but it's fine for the team to do so as both issues are for the same core problem.
