### ISSUE TITLE
[ Minor ] - homepage - video here creates a sliding effect on mobile

### ISSUE THREAD

**Issue by angelinapoltavskiy** [info442-aut21/c-team#102]
When I opened up the application on my phone, on the homepage and resources page there is a really big video that creates a sliding effect, where on the second half of the screen is just the extended video
environment: iphone XR, safari browser
steps to reproduce: open up application on mobile device, you should see the issue on the homepage
expected result: when I open up the application on mobile, there would be a full shop of the homepage and resources page
actual result: when I open up the application on mobile there is a slider to accommodate for the oversized video on the homepage and resources page

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/94
