### ISSUE TITLE
[Minor] Date of Post is One Month Behind

### ISSUE THREAD

**Issue by Jemuelle4** [info442-aut21/c-team#103]
description: When posting a new post/mood, the date is one month behind 
●     environment: Firefox 94.0.1 (32-bit), Windows 10
●     Go to Home/Feed. Create a new post by clicking on the plus button. Fill out the fields. Press Post.
●     expected result - Date: 11/22/2021
●     actual result - Date: 10/22/2021

**Comment by julianedelossantos** [comment]
-this issue was able to be reproduced on Windows 11 Chrome Browser
-we will work on our homepage to fix the function in charge of recording the current date and saving that information to a post object
