### ISSUE TITLE
[Minor] Under Resources, 31 Tips to Boost Your Mental Health post does not connect/show up

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/c-team#104]
<img width="637" alt="Screen Shot 2021-11-22 at 09 45 56" src="https://user-images.githubusercontent.com/59168497/142909989-47a8c595-a39e-4d49-a2da-c339ee2793a3.png">

This was tested on MacOS Monterey and Google Chrome Version 96.0.4664.45. 

1. Not logged in, navigate to Resources
2. Scroll down to 31 Tips to Boost Your Mental Health
3. 
Expected result: Content under "31 Tips to Boost Your Mental Health
Actual result: "www.mhanational.org refused to connect" error

**Comment by julianedelossantos** [comment]
Duplicate with #85
