### ISSUE TITLE
[Feature Request] Able to view/see the password

### ISSUE THREAD

**Issue by naishg** [info442-aut21/c-team#107]
Having some sort of button where users are able to click to see the password they typed out. This helps to minimize users typing error when trying to create a password. This also helps users to see if the password they typed matches or not.

**Comment by julianedelossantos** [comment]
-we will add a toggle-able checkbox to change the format of the textbox to allow the user to see the characters they are typing in and it's also good for testing to confirm we are typing in correct testing passwords
