### ISSUE TITLE
[Minor] Incorrect Password Prompt

### ISSUE THREAD

**Issue by IamSuperB4** [info442-aut21/c-team#111]
Windows 11:
Google Chrome: Version 96.0.4664.45

I typed in my credentials on the signup page, with the password: info442Pa$$word, then a non-matching password: notsamepassword (I also tried "not$amePassword1"). I was alerted that:
Error: password must contains at least 8 characters, 1 uppercase letter, 1 special character (on a standard qwerty keyboard), and 1 number

Expected: I was expecting the site to tell me that the password don't match, not that I don't have a valid password. I even typed 2 passwords (one in password, one in conform password) that met the criteria and it still told gave me the same error.
Actual: Was prompted that my password did not meet the criteria

**Comment by IamSuperB4** [comment]
I also typed in the correct and matching passwords (info442Pa$$word) and it gave me the same error after going through this entire process

**Comment by julianedelossantos** [comment]
Duplicate with #81

**Comment by cherimarie** [comment]
For development purposes, I can see how this is a duplicate with #81, but for @IamSuperB4 's phase 7 grade, I won't be counting it as a duplicate.
