### ISSUE TITLE
[Major] Starred Posts not Saved in My Profile

### ISSUE THREAD

**Issue by sershon** [info442-aut21/c-team#113]
Expected: Clicking the star icon on a post adds it to the "Saved" section of my profile.
Reality: Clicking on the stars does not seem to have any effect.
Steps to recreate: Click the star icons on posts on the homepage, and then go to my profile, and saved posts.
Found on MacOS Monterey and Google Chrome Version 95.0.4638.69 (Official Build) (arm64)

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/101

**Comment by cherimarie** [comment]
I can see why this is marked a duplicate, but for purposes of Jesse's grade, I'm not counting it as such.
