### ISSUE TITLE
[Enhencement] Could make your own website name and icon on the browser tag

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/c-team#114]
environment it was encountered in: Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Open the site on browser like Chorme 
expected result: A unique website tag name and icon 
actual result: react default setting of name and logo.
<img width="263" alt="Screen Shot 2021-11-22 at 10 39 10 AM" src="https://user-images.githubusercontent.com/59670580/142916934-d93a4661-c7b7-4c29-a870-b99e139e1dee.png">

**Comment by julianedelossantos** [comment]
-we will convert our website logo to a favicon.ico and use that for the website icon
-we will change the title of the website on all pages to be "SafeSpace" with an extension " - [name of page]" for every available page to the user
