### ISSUE TITLE
[Major] Already signed into someone else's account without signing in 

### ISSUE THREAD

**Issue by naishg** [info442-aut21/c-team#115]
Description: When I open the website, I was already signed into some tester account which was created before hand without actually having to signing in.  

Expectation: Did not expect to being signed in without having added any credentials

Environment: MacOS BigSur Safari Version 15.0 (16612.1.29.41.4, 16612)

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/110
