### ISSUE TITLE
[Enhancement] Add post button overlaps with the rest of the screen when on mobile view

### ISSUE THREAD

**Issue by naishg** [info442-aut21/c-team#116]
Description: When navigating through the website on the mobile view, the add post button is very big and it can distract users from reading the actual post. 
Expected: Better sizing the button so that its not too big
Environment: iPhone XS, Safari

**Comment by julianedelossantos** [comment]
Tested on iPhone 8+ device and iPhoneX mobile screen through desktop browser inspect element and the add post button did not seem like an issue

**Comment by cherimarie** [comment]
For @naishg's phase 7 grade, this should have been a bug, not a feature request. Counting it as such.
