### ISSUE TITLE
[Enhancement] Full screening the videos is not a function communicated to the user

### ISSUE THREAD

**Issue by aramos10-1863966** [info442-aut21/c-team#118]
Description: When testing the embedded videos, I played them and immediately thought to full screen the videos since many of them are embedded YouTube videos. However, the icon for full-screening a video was not present in the bottom right, thus I originally thought full screening wasn't possible until I clicked my 'F' key for full screen. Something I know is possible because I watch a lot of YouTube.

Expectation: Full screen icon present on the video for users who don't know keyboard shortcuts.

Environment: Microsoft Edge Version 96.0.1054.29

**Comment by julianedelossantos** [comment]
-we plan to replace the ReactPlayer with iFrame HTML elements for onboarding and resources page in order to edit the videos' ability to be full-screened across multiple devices using advice from https://www.bitdegree.org/learn/how-to-embed-a-youtube-video
