### ISSUE TITLE
[Minor] Navbar & Screens are compressed on Mobile 

### ISSUE THREAD

**Issue by talajune** [info442-aut21/c-team#119]
Device: Apple Iphone 12 Pro, Safari
Summary of problem: the Profile tab on the navbar is not in line with the other tabs on the navbar. It is below the "about us" tab and the black color of the navbar is also shorter than the entire width of the screen. 
steps to reproduce: fix navbar styling in CSS
expected result: navbar to be evenly across the screen with all tabs along the same line
actual result: the "profile" tab is below the "about us" tab 

Also, overall the screen looks compressed and not aligned on my iPhone screen, I think elements are in different places and are misaligned. 

![IMG_7509](https://user-images.githubusercontent.com/76933462/143160587-c90f2fd4-f0a7-4a39-a912-f8f7e8e7d7c1.PNG)
![IMG_7507](https://user-images.githubusercontent.com/76933462/143160585-53e042b7-5065-40b5-a21e-31c6c499639a.PNG)
:

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/108
