### ISSUE TITLE
[Enhancement] Add a Table of Contents for the Resources page

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/c-team#120]
Description: Add a Table of Contents box to the Resources page, similar to how a Wikipedia page has a Table of Contents box (i.e. attached image) that summarizes the content on the page. Users can click on each link in the ToC box and there page will automatically scroll to that resource on the page.

Explanation: I think this would be useful for users to see what resources are available at a quick glance without having to scroll down the page. It would also allow users to quickly go to that part of the page that has that resource without having to scroll through one or more resources to reach the one they're looking for.

<img width="235" alt="Screen Shot 2021-11-23 at 7 43 39 PM" src="https://user-images.githubusercontent.com/56002881/143181882-7c494c4c-b0fa-4a0c-acf0-552beb718e1e.png">

**Comment by julianedelossantos** [comment]
-if we have a ton of resources on this page, a table of contents would make sense to navigate easily through the headers; however, it was a design choice to not add quick navigation as our header order encourages our users to take the steps they see first
