### ISSUE TITLE
[Major] too many characters in a post does not move down a line but continues to the right of the screen beyond the page

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/c-team#131]
Onboard > Log In > New post > Type in "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" > Post > Returns post that spills over to the right beyond the boundaries of the html

Ideally should drop down a line once the characters reach the edge of the post box

**Comment by ayun6** [comment]
fixed with overflow-wrap in css; now additional characters continue in new line below
