### ISSUE TITLE
[major] All user credentials are being logged in the console

### ISSUE THREAD

**Issue by cherimarie** [info442-aut21/c-team#137]
Even for a simple class project, we should never be logging user credentials. Anything in the browser is visible to users and bad actors.

<img width="859" alt="Screen Shot 2021-12-01 at 7 00 37 AM" src="https://user-images.githubusercontent.com/2523812/144258305-377ffd4e-5e39-4e77-acdf-8327ef649c45.png">

**Comment by julianedelossantos** [comment]
The console.log statements from testing have been removed as per our security requirement
