### ISSUE TITLE
[Minor] Sign In with Incorrect Password

### ISSUE THREAD

**Issue by judysdesign** [info442-aut21/c-team#146]
macOS Big Sur
Version 11.6
Chrome Version 96.0.4664.55

Description: When signing in with the correct email and wrong password. The user doesn't know what happened or if the password matched with the account.
Expected: Should get a message saying that password doesn't match with the account. Prompts the user reset their password or to try again.
Actual: Password field is just cleared.

**Comment by julianedelossantos** [comment]
Error message is now available if the user credentials are incorrect. Password field is still cleared.
