### ISSUE TITLE
Usability/Accessibility

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/c-team#30]
This issue cannot be completed until milestone "Interactive Application" is complete and issue #35 is completed.

- The application will be run on the latest versions chrome, safari, firefox, and edge with no issues
- The WAVE contrast checker will present acceptable ratios
- The W3C Markup Validator will return no errors

This ticket completes the requirements 9.3, 9.4, 9.5

**Comment by ayun6** [comment]
tested on all latest versions of chrome, safari, firefox, and edge with no issues
WAVE contrast checker presents 0 contrast errors
W3C Markup Validator returns no errors or warnings
