### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/c-team#31]
This issue cannot be completed until milestone "Interactive Application" is complete.

- The application will return a score of at least 90 on Google Page Speed Insights
- Navigation tabs will route the user to appropriate pages within 1 second
- Submitting forms will make appropriate changes to the database within 3 seconds

This ticket completes the requirements 8.1, 8.2, 8.3

**Comment by ayun6** [comment]
tested with a score of 94 for desktop on Google Page Speed Insights
navigation tabs route the user to appropriate pages within 1 second and submitting forms make appropriate changes to the database within 3 seconds
