### ISSUE TITLE
[MAJOR]There is a view profile option even when not signed in

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/c-team#80]
Description: The Navbar contains under the profile drop-down sign out and views profile options even when I'm not signed in
Expected: The profile should show an option to sign in/ Log in.
Actual:It shows a link to view the profile or sign out.
<img width="1440" alt="Screen Shot 2021-11-23 at 10 11 56 PM" src="https://user-images.githubusercontent.com/56050100/143184491-871da96c-612a-4db7-bf69-5fbcb5e5bb7b.png">

Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

**Comment by julianedelossantos** [comment]
-user authentication will display different options depending on if the user is logged in or not
-the default session would be changed to have the user not logged in
-if not logged in, they will have a "sign in" option on all screens
-if logged in, they will have the options of "view my profile" and "log out"

**Comment by julianedelossantos** [comment]
User authentication has been implemented
