### ISSUE TITLE
[Major] when creating an account, if the password is correctly filled in following parameters, and the other areas are blank the error states the password reqs instead of saying the email field is empty

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/c-team#81]
- [Major] when creating an account, if the password is correctly filled in following parameters, and the other areas are blank the error states the password reqs instead of saying the email field is empty
- Firefox on Windows 10
- clicked get started button on landing page and filled out only the password elements in form according to reqs
- expected for error to say to fill out email, instead error stated the password reqs
- actual result is error stating password reqs

**Comment by julianedelossantos** [comment]
-we plan to add more specific error messages for different error states
-we plan to add multiple error messages at the same to address multiple mistakes during the sign up process
-we plan to specify "special character" options in that respective password error message
