### ISSUE TITLE
[Major] The password for the sign up from is not validated properly

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/c-team#82]

**Comment by palashgujrathi** [comment]
Description: Even though the entered password meets all the requirements, the application will still not accept the it.
Expectation: if an entered password meets all the requirements, user should be allowed to sign up.
Environment: macOS Monterey Safari Version 15.1 (17612.2.9.1.20)

**Comment by julianedelossantos** [comment]
Duplicate with https://github.com/info442-aut21/c-team/issues/81
