### ISSUE TITLE
[Major] Search bar not working in the feed

### ISSUE THREAD

**Issue by palashgujrathi** [info442-aut21/c-team#83]
description: The search bar in not functional.
expectations: expected to return the results for the keywords entered.
environment: macOS Monterey safari Version 15.1

**Comment by julianedelossantos** [comment]
-we plan to have the search bar return results after the search button is clicked with all post information (tags, content, date) that contains the phrase(s) typed into the search bar in order of most recent
-currently, the search bar is not functional
