### ISSUE TITLE
[Major] Search bar is not responsive

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/c-team#84]
Description: Search button does not perform or produce a response

Steps to Reproduce:

1. Go to home (feed) page
2. Type into search bar
3. Apply search either by pressing "search " button
Expected: I expected it to show up search results for the keywords.
Actual:the page remains the same and does not reload or produce an output
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by julianedelossantos** [comment]
Duplicate
