### ISSUE TITLE
[Minor]images rendering errors for the 31 tips to boost your metal health

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/c-team#85]
Description: The image for this doesn't load a grey picture is displayed
Expected: The cover photo of the blog is dislpayed
Actual: The image is not displayed
Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

<img width="1032" alt="Screen Shot 2021-11-22 at 9 31 08 AM" src="https://user-images.githubusercontent.com/56050100/142907944-1434771e-f9ba-42eb-8023-b066fe158275.png">

**Comment by julianedelossantos** [comment]
-we plan to find an alternative link that doesn't have an issue with cookie acceptance so that it can successfully render on our page
