### ISSUE TITLE
[Major] "31 Tips to Boost Your Mental Health" Media Not Showing Up On Resources Page

### ISSUE THREAD

**Issue by talajune** [info442-aut21/c-team#86]
<img width="1440" alt="Screen Shot 2021-11-22 at 9 29 10 AM" src="https://user-images.githubusercontent.com/76933462/142907731-40368dd3-6082-41f2-94da-2c3a04a2e44b.png">

The media for the "31 Tips to Boost Your Mental Health" article under the Resources Page is not loading/showing up on my screen. It shows a grey screen and says "www.mhanational.org refused to connect."
Device: MacOS Big Sur Chrome v95.0.4638.69

**Comment by julianedelossantos** [comment]
Duplicate

**Comment by cherimarie** [comment]
For grading purposes, I'm not counting this a dupe, as it was submitted only 1 minute after 85.
