### ISSUE TITLE
[Enhencement] Sign in message on the landing page is at the bottom 

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/c-team#87]
When user first enter the site, they have to scroll down to be able to see the sign in. It's better to make them appear along with the video, just need to rearrange the position. 

environment it was encountered in: ChromeVersion 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Landing page when first open the site
expected result: Now what to do next/there is a sign in function. 
actual result: Sitting for a bit not sure what to do until I scroll down and see the sign in function. Has to try clicking Home to move on.

**Comment by julianedelossantos** [comment]
-we plan to edit the styling to have all of the information on the onboarding page that doesn't require the user to scroll

**Comment by julianedelossantos** [comment]
-after further deliberation on how elements are seen on the onboarding page, we've edited the size of components to appeal to the UI, which requires a bit of scrolling
