### ISSUE TITLE
[Minor] on resources page the site linked under "31 Tips to Boost Your Mental Health" is unreachable by firefox in the preview, user would have to open this link in a new window

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/c-team#88]
- [Minor] on resources page the site linked under "31 Tips to Boost Your Mental Health" is unreachable by firefox in the preview, user would have to open this link in a new window
- Firefox on Windows 10
- on resources page scrolled down to see "Tips to Boost Your Mental Health"
- expected to see preview of webpage
- actual result: firefox cannot open webpage 
- 
![image](https://user-images.githubusercontent.com/68711218/142908059-9fd72db2-7b1d-42bd-b005-abb9b915c78e.png)

**Comment by julianedelossantos** [comment]
Duplicate for other browsers
