### ISSUE TITLE
[Minor] "View my profile page" is logged in as test user when not signed in

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/c-team#89]
Description: View my profile page is automatically logged in as test user when not signed in

Environment: Mac OS Big Sur Google Chrome 96.0.4664.55

Steps: on click view my page, an empty profile should appear

Expected: An empty profile screen
Actual: test user screen

**Comment by manyaj57** [comment]
additional notes: able to edit the test user profile as well

**Comment by Jemuelle4** [comment]
Additional notes: Once the profile is edited and the user goes on other pages, when coming back to the profile, the profile is back to "testuser" as name

**Comment by Skylitmoon** [comment]
Additional notes: When signing out and then clicking View my profile, it goes back to the testuser account

**Comment by julianedelossantos** [comment]
Duplicate
