### ISSUE TITLE
[Minor] Sign Out Button Present Even When Not Signed In

### ISSUE THREAD

**Issue by nsnatthapat** [info442-aut21/c-team#92]
Environment: Chrome Version 95.0.4638.69 (Official Build) (x86_64) on MacOS Monterey

Steps to Reproduce:
1. Go to Profile from Navbar

Expected: If not signed in, to see sign in button
Actual: "View my profile" and "Sign Out" are there regardless of signed in status

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/80
