### ISSUE TITLE
[Minor Usability Issue] Not sure what the search bar can do (don't mean it is not functional)  

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/c-team#93]
The user is confused on what they can do with the search bar. They can search for tags and post, but this could be done by using control+f or command +f using the website search function.

environment it was encountered in: Google Chorme Version 95.0.4638.69 (Official Build) (arm64) 
steps to reproduce: Pretend the seach is working functionally, hit control+f (using the browser search) could also acheive this.
expected result: Search bar could do something special that the browser search cannot do. Or expected to know what the search bar can do.
actual result: Just a normal search bar. Not sure whats the difference between the browser search.

**Comment by ayun6** [comment]
duplicate issue https://github.com/info442-aut21/c-team/issues/83

**Comment by cherimarie** [comment]
For grading purposes, I'm not going to mark this as a duplicate. I believe the two reports differ because #83 is a functional bug, and this one is a usability bug.
