### ISSUE TITLE
[Major] Site size and videos not responsive to Iphone 7/smaller screens

### ISSUE THREAD

**Issue by Vivianngu3** [info442-aut21/c-team#94]

**Comment by Vivianngu3** [comment]
![IMG_8265](https://user-images.githubusercontent.com/62910701/142914380-295c84b8-4ec7-43eb-838c-8bd8bde709f3.PNG)
Encountered: Iphone7
Description: Content on the site does not fit on the smaller screen and instead needs to be zoomed out
Steps to reproduce: Opening the site on Mobile
Expected results: Content to fit on screen
Actual results: Spills over the size and have to zoom out but content size is inconsistent

**Comment by julianedelossantos** [comment]
-we will implement responsive styling in our css through media queries and non-px values for the sizing of objects that display or extent awkwardly on each page
