### ISSUE TITLE
[Major] favorite posts on feed go back to default after refresh 

### ISSUE THREAD

**Issue by palashgujrathi** [info442-aut21/c-team#95]
Description: after clicking the star button on the post in feed to make it favorite and after refreshing the page, it goes back to default values.

Expected: I expected it to be in the new values for the user to know which one's are their favorite.

Environment: macOS Monterey Safari Version 15.1 (17612.2.9.1.20)

**Comment by julianedelossantos** [comment]
-connect functionality of the save post button to the user object in our database and have that display on the profile page (issue unresolved from original requirements)
