### ISSUE TITLE
[Enhancement] Add a welcome screen/pop up with a TW/Sensitive topic message

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/c-team#96]
Description: Add a pop-up/welcome screen that states that this website will be talking about sensitive topics. 

This would be useful because many people would feel an emotional reaction when talking about the concept of suicide. People should be prepared and choose to enter this space beforehand.

**Comment by julianedelossantos** [comment]
-instead of a user session pop-up, we will address this issue by indicating a trigger warning section on the onboarding page
